stages:
  - build
  - deploy_gcp

build_images:
  stage: build
  image: docker:20.10.16

  services:
    - docker:20.10.16-dind
  
  variables: 
    DOCKER_TLS_CERTDIR: "/certs"

  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS

  script:
    - docker build -t jefersont/devops_desario06:1.0 app/.
    - docker push jefersont/devops_desario06:1.0

deploy_gcp:

  stage: deploy_gcp

  before_script:
    - chmod 400 $SSH_KEY
  
  script:
      - ssh -o StrictHostKeyChecking=no -i $SSH_KEY gcp@$SSH_SERVER "sudo rm -Rf ./dio-cloud_devops_experience-desafio06/ && sudo git clone https://github.com/JefersonT/dio-cloud_devops_experience-desafio06.git && cd dio-cloud_devops_experience-desafio06 && sudo chmod +x ./script.sh && ./script.sh"

